#learn about python numpy and installing numpy


In [1]:
import numpy as np

##creating arrays 


In [3]:
print_1d_array=np.array([1, 2, 3, 4, 5])
print(print_1d_array)
array2d=np.array([[1, 2, 3], [4, 5, 6]])
print(array2d)

[1 2 3 4 5]
[[1 2 3]
 [4 5 6]]


#list vs array

In [6]:
printmultiplication=[1, 2, 3, 4, 5]
print(printmultiplication * 2)

printNPmultiplication=np.array([1, 2, 3])
print(printNPmultiplication * 2)

s="s"

print(s*2)

[1, 2, 3, 4, 5, 1, 2, 3, 4, 5]
[2 4 6]
ss


In [11]:
created_list_array=np.arange(20)
print(created_list_array)


import time as t

start_time=t.time()

list_array=[i*2 for i in range (1000000)]
print("List creation time:", t.time() - start_time)



NP_array=np.arange(1000000) * 2
print("Numpy array creation time:", t.time() - start_time)


[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]
List creation time: 1.7119905948638916
Numpy array creation time: 1.7576303482055664


###creating array from scratch

In [14]:
zeros = np.zeros((2, 3))
print(zeros)


ones = np.ones((2, 4))
print(ones)

full = np.full((2, 2), 8)
print(full)

randarr =np.random.random((2, 4))*10
print(randarr)


seq = np.arange(0, 21, 3)
print(seq)

[[0. 0. 0.]
 [0. 0. 0.]]
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]]
[[8 8]
 [8 8]]
[[9.24002921 2.40097613 1.95281102 4.94469429]
 [5.08988059 1.47364519 3.65690027 6.80359291]]
[ 0  3  6  9 12 15 18]



vector, matrix, tensor

In [20]:
vector =np.array([1, 2, 3])
print(vector)

matrix =np.array([[1, 2, 3], [4, 5, 6]])
print(matrix)

tensor=np.array([[[1, 2], [3, 4]],
                [[5, 6], [7, 8]]])

print(tensor)

[1 2 3]
[[1 2 3]
 [4 5 6]]
[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


###array properties

In [22]:
arr =np.array([[1, 2, 3], [4, 5, 6]])

shape=arr.shape
dimension =arr.ndim
size =arr.size
dtype =arr.dtype

print(shape)
print(dimension)
print(size)
print(dtype)

(2, 3)
2
6
int64


array reshaping

In [39]:
arrSec =np.array((1, 2, 3, 4, 5, 1, 2, 3, 4, 5, 6, 7))

arrReshape=arrSec.reshape((3, 4))
arrFlat=arrReshape.flatten()
arrRaveled =arr.ravel()
transpose=arrReshape.T
print(arrSec)
print(arrReshape)
print(arrFlat)
print(arrRaveled)
print(transpose)


[1 2 3 4 5 1 2 3 4 5 6 7]
[[1 2 3 4]
 [5 1 2 3]
 [4 5 6 7]]
[1 2 3 4 5 1 2 3 4 5 6 7]
[1 2 3 4 5 6]
[[1 5 4]
 [2 1 5]
 [3 2 6]
 [4 3 7]]
