1d array slicing

In [2]:
import numpy as np

In [3]:
arr_1d =np.array([1, 2, 3, 4, 5, 6, 7, 8, 9])
print(arr_1d[3:6])
print(arr_1d[2:8:2])
print(arr_1d[-3])

[4 5 6]
[3 5 7]
7


2d_array slicing

In [ ]:
arr_2d=np.array([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

print(arr_2d[1, 2])
print(arr_2d[2])
print(arr_2d[:, 1])

6
[7 8 9]
[2 5 8]


###sorting

In [17]:
arr_sort_1d =np.array([1, 2, 1, 4, 5, 2, 8, 8, 9, 4, 6, 7])
print(np.sort(arr_sort_1d))

#multi dimensional array sort

arr_sort_2d= np.array([[17, 45, 83],
 [92, 4, 67],
 [23, 88, 56],
 [41, 70, 12]])

print(np.sort(arr_sort_2d, axis=0))
print()
print(np.sort(arr_sort_2d, axis=1))

[1 1 2 2 4 4 5 6 7 8 8 9]
[[17  4 12]
 [23 45 56]
 [41 70 67]
 [92 88 83]]

[[17 45 83]
 [ 4 67 92]
 [23 56 88]
 [12 41 70]]


filter

In [18]:
arr_filter =np.array([1, 2, 1, 4, 5, 2, 8, 8, 9, 4, 6, 7])
print(arr_filter[arr_filter %2==0])

[2 4 2 8 8 4 6]


filter with mask

In [7]:
arr_filter =np.array([1, 2, 1, 4, 5, 2, 8, 8, 9, 4, 6, 7])
mask = arr_filter<5
print(arr_filter[mask])

[1 2 1 4 2 4]


fancy indexing vs where()

In [9]:
ind =[0, 2, 4]
print(arr_filter[ind])

where_res =np.where(arr_filter>4)
print(arr_filter[where_res])



[1 1 5]
[5 8 8 9 6 7]


In [21]:
arr_filter =np.array([1, 2, 1, 4, 5, 2, 8, 8, 9, 4, 6, 7])
condition_arr=np.where(arr_filter<=2, arr_filter+2, arr_filter)
print(arr_filter[condition_arr])

[4 5 4 5 2 5 9 9 4 5 8 8]


adding and removing data

In [22]:
arr_1=np.array([1, 2, 3])
arr_2=np.array([5, 4, 9])

combine=np.concatenate((arr_1, arr_2))
print(combine)

[1 2 3 5 4 9]


array compatiablity

In [26]:
a=np.array([1, 2, 3])
b=np.array([5, 4, 9])
c=np.array([5, 4, 9, 7])

result = a.shape==b.shape
result2 = b.shape==c.shape
print("first result ", result, "second result ", result2)

first result  True second result  False


In [28]:
ogArr= np.array([[1, 2, 3], [5 ,4, 6]])
new_arr=np.array([[7, 8, 9]])
new_col_arr=np.array([[7], [8]])

new_row =np.vstack((ogArr, new_arr))
print(new_row)

new_col =np.hstack((ogArr, new_col_arr))
print(new_col)

[[1 2 3]
 [5 4 6]
 [7 8 9]]
[[1 2 3 7]
 [5 4 6 8]]


In [29]:
deleteArr= np.array([1, 2, 3, 5 ,4, 6])

delete=np.delete(deleteArr, 3)
print(delete)

[1 2 3 4 6]
